### ISSUE TITLE
QtQuick.Controls is not installed

### ISSUE THREAD

**Issue by yukulele** [Risu/DisplayBrightnessControl#1]
When I click on icon I get this error:

> Error loading QML file: ~/.local/share/plasma/plasmoids/risu.brightness.bar/contents/ui/main.qml:6:1: module "QtQuick.Controls" version 1.6 is not installed

Is there some install requirements to use *Display Brightness Control*?

I'm on ubuntu 18.04 + plasma.

**Comment by Risu** [comment]
Seems like installed QT version is too old. Current Ubuntu LTS release is Focal, don't you plan to upgrade anyway?
Related help:
[https://unix.stackexchange.com/questions/481063/ubuntu-18-04-1-lts-x64-how-to-update-qt-5-10-from-qt-5-9-5](https://unix.stackexchange.com/questions/481063/ubuntu-18-04-1-lts-x64-how-to-update-qt-5-10-from-qt-5-9-5)
